services:
  lightrag-2:
    container_name: lightrag-2
    image: ghcr.io/hkuds/lightrag:latest
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ghcr.io/hkuds/lightrag:latest
    ports:
      - "${PORT:-9622}:9621"
    volumes:
      - ./lightrag/prompt.py:/app/lightrag/prompt.py
      - ./lightrag/operate.py:/app/lightrag/operate.py
      - ./lightrag/config/annotation_memory.json:/app/lightrag/config/annotation_memory.json
      - ./lightrag/config/profiles:/app/lightrag/config/profiles
      - ./lightrag/utils_graph.py:/app/lightrag/utils_graph.py
      - ./lightrag/lightrag.py:/app/lightrag/lightrag.py
      - ./lightrag/api/config.py:/app/lightrag/api/config.py
      - ./lightrag/api/routers/document_routes.py:/app/lightrag/api/routers/document_routes.py
      - ./data:/app/data
      - ./config.ini:/app/config.ini
      - ./tools/clean_annotation_memory.py:/app/tools/clean_annotation_memory.py
      - ./.env:/app/.env
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
